### ISSUE TITLE
Make test fails

### ISSUE THREAD

**Issue by lbarman** [turingwars/turingwars#39]
```
$ make test

> tsc --noEmit && tslint -p . && jest

The 'no-inferred-empty-object-type' rule threw an error in '/home/jwhite/d/git/turingwars/web/src/assembler/Parser.ts':
RangeError: Maximum call stack size exceeded
    at getIndexInfoOfStructuredType (/home/jwhite/d/git/turingwars/web/node_modules/typescript/lib/typescript.js:35862:46)
    at getIndexTypeOfStructuredType (/home/jwhite/d/git/turingwars/web/node_modules/typescript/lib/typescript.js:35869:24)
    at Object.getIndexTypeOfType (/home/jwhite/d/git/turingwars/web/node_modules/typescript/lib/typescript.js:35880:20)
    at TypeObject.getNumberIndexType (/home/jwhite/d/git/turingwars/web/node_modules/typescript/lib/typescript.js:110999:33)
    at NoInferredEmptyObjectTypeRule.isEmptyObjectInterface (/home/jwhite/d/git/turingwars/web/node_modules/tslint/lib/rules/noInferredEmptyObjectTypeRule.js:96:21)
    at /home/jwhite/d/git/turingwars/web/node_modules/tslint/lib/rules/noInferredEmptyObjectTypeRule.js:100:62
    at Array.every (<anonymous>)
    at NoInferredEmptyObjectTypeRule.isEmptyObjectInterface (/home/jwhite/d/git/turingwars/web/node_modules/tslint/lib/rules/noInferredEmptyObjectTypeRule.js:98:41)
    at /home/jwhite/d/git/turingwars/web/node_modules/tslint/lib/rules/noInferredEmptyObjectTypeRule.js:100:62
    at Array.every (<anonymous>)
The 'no-inferred-empty-object-type' rule threw an error in '/home/jwhite/d/git/turingwars/web/src/assembler/Tokenizer.ts':
RangeError: Maximum call stack size exceeded
    at Object.getPropertiesOfType (/home/jwhite/d/git/turingwars/web/node_modules/typescript/lib/typescript.js:35447:17)
    at TypeObject.getProperties (/home/jwhite/d/git/turingwars/web/node_modules/typescript/lib/typescript.js:110981:33)
    at NoInferredEmptyObjectTypeRule.isEmptyObjectInterface (/home/jwhite/d/git/turingwars/web/node_modules/tslint/lib/rules/noInferredEmptyObjectTypeRule.js:95:21)
    at /home/jwhite/d/git/turingwars/web/node_modules/tslint/lib/rules/noInferredEmptyObjectTypeRule.js:100:62
    at Array.every (<anonymous>)
    at NoInferredEmptyObjectTypeRule.isEmptyObjectInterface (/home/jwhite/d/git/turingwars/web/node_modules/tslint/lib/rules/noInferredEmptyObjectTypeRule.js:98:41)
    at /home/jwhite/d/git/turingwars/web/node_modules/tslint/lib/rules/noInferredEmptyObjectTypeRule.js:100:62
    at Array.every (<anonymous>)
    at NoInferredEmptyObjectTypeRule.isEmptyObjectInterface (/home/jwhite/d/git/turingwars/web/node_modules/tslint/lib/rules/noInferredEmptyObjectTypeRule.js:98:41)
    at /home/jwhite/d/git/turingwars/web/node_modules/tslint/lib/rules/noInferredEmptyObjectTypeRule.js:100:62
```

**Comment by hmil** [comment]
This is not a critical failure. It's most likely a bug in the tslint rule `no-inferred-empty-object-type` which is ignored.
