### ISSUE TITLE
Can't build the engine anymore

### ISSUE THREAD

**Issue by lbarman** [turingwars/turingwars#52]
```
~/d/git/turingwars/engine/turingwars(master) » sbt test                                                                                                                

[info] Fast optimizing /home/jwhite/d/git/turingwars/engine/turingwars/target/scala-2.12/turingwars-engine-test-fastopt.js
Scala.js Com failed: Error: connect EHOSTUNREACH 192.168.1.128:33163
[error] org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: Node.js exited with code 255
[error] 	at org.scalajs.jsenv.ExternalJSEnv$AbstractExtRunner.waitForVM(ExternalJSEnv.scala:114)
[error] 	at org.scalajs.jsenv.ExternalJSEnv$AsyncExtRunner$$anon$1.$anonfun$run$2(ExternalJSEnv.scala:179)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at scala.util.Try$.apply(Try.scala:209)
[error] 	at org.scalajs.jsenv.ExternalJSEnv$AsyncExtRunner$$anon$1.run(ExternalJSEnv.scala:179)
[error] (test:loadedTestFrameworks) org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: Node.js exited with code 255
[error] Total time: 37 s, completed Oct 6, 2018 2:32:48 PM
```

**Comment by hmil** [comment]
Can't reproduce

**Comment by lbarman** [comment]
Fixed indeed, ty
